# Generated by Django 3.2.8 on 2021-10-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('jersey_no', models.IntegerField()),
                ('role', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
